<?php
// -------------------------------
// Constantes para tipos de apartados
// -------------------------------

// COMÚN
define('TIPO_APARTADO_EDITABLE', 0);

// PROGRAMACIONES
define('TIPO_APARTADO_CONTEXTO', 1);
define('TIPO_APARTADO_RELACION_UC_MODULOS', 2);
define('TIPO_APARTADO_RELACION_RA_COMPETENCIAS', 3);
define('TIPO_APARTADO_SECUENCIA_TEMAS', 4);
define('TIPO_APARTADO_FE', 5);
define('TIPO_APARTADO_RA_CE', 6);
define('TIPO_APARTADO_EVALUACION_RA', 10);
define('TIPO_APARTADO_TEMAS', 13);

// PCCF
define('TIPO_APARTADO_PCCF_IDENTIFICACION', 1);
define('TIPO_APARTADO_PCCF_COMPETENCIAS_PROFESIONALES', 4);
define('TIPO_APARTADO_PCCF_COMPETENCIAS_EMPLEABILIDAD', 5);
define('TIPO_APARTADO_PCCF_DISTRIBUCION_MODULOS', 7);
define('TIPO_APARTADO_PCCF_RA_EMPRESA', 101);
?>